"""add new columns to goal

Revision ID: 80b351d16657
Revises: 5effaafb5b88
Create Date: 2026-01-05 15:53:04.497297

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "80b351d16657"
down_revision: Union[str, Sequence[str], None] = "5effaafb5b88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("goals", sa.Column("name", sa.String(), nullable=False))
    op.drop_index(op.f("ix_goals_description"), table_name="goals")
    op.create_index(op.f("ix_goals_name"), "goals", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_goals_name"), table_name="goals")
    op.create_index(
        op.f("ix_goals_description"), "goals", ["description"], unique=True
    )
    op.drop_column("goals", "name")
    # ### end Alembic commands ###
