"""add deadline day on goals

Revision ID: 78a637dc86a6
Revises: 80b351d16657
Create Date: 2026-01-05 15:55:55.313679

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78a637dc86a6"
down_revision: Union[str, Sequence[str], None] = "80b351d16657"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "goals", sa.Column("deadline_day", sa.Date(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("goals", "deadline_day")
    # ### end Alembic commands ###
