"""add nullable to last_naem

Revision ID: 5effaafb5b88
Revises: b48f9544e09d
Create Date: 2026-01-05 14:38:08.300303

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5effaafb5b88"
down_revision: Union[str, Sequence[str], None] = "b48f9544e09d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "persons", "last_name", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "persons", "last_name", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
