import random

motivational_phrases = [
    "Turn your dreams into plans.",
    "With every choice, you determine your future.",
    "Suffer now and live the rest of your life as a champion.",
    "Train like there’s no finish line.",
    "A goal without a plan is a wish.",
    "Take action, and your dreams will come alive.",
    "Your only competition is yourself.",
    "Focus on your strengths.",
    "Every setback is a setup for a comeback.",
    "Push your limits; greatness awaits.",
    "You are stronger than you think!",
    "Champions are made in the off-season.",
    "Hard work beats talent when talent doesn’t work hard.",
    "Believe in yourself and all that you are.",
    "Train hard, play hard.",
    "Success starts with self-discipline.",
    "Stay focused; the finish line is near.",
    "Your only limit is you.",
    "Dream big, work hard, achieve.",
    "Dedication is the key to success.",
    "Winners never quit, and quitters never win.",
    "Every day is an opportunity to improve.",
    "Strive for progress, not perfection.",
    "Hustle and heart set you apart.",
    "Success is earned, not given.",
    "Fuel your passion, ignite your spirit.",
    "Every champion was once a contender.",
    "Make each workout count.",
    "Victory loves preparation.",
    "The pain you feel today will be the strength you feel tomorrow.",
    "Turn your dreams into goals.",
    "Embrace the grind.",
    "Set your goals high and don't stop.",
    "Be fearless in the pursuit of what sets your soul on fire.",
    "Focus on the journey, not the destination.",
    "Your effort determines your outcome.",
    "Sweat is just fat crying.",
    "Consistency is the backbone of success.",
    "Play like there’s no tomorrow.",
    "Every drop of sweat brings you closer.",
    "Get up, get after it!",
    "Your mind gives up before your body does.",
    "Find your passion and let it fuel you.",
    "Champions are made by doing what others won’t.",
    "Train like a beast, look like a beauty.",
    "Determination knows no bounds.",
    "Stay hungry for success.",
    "Act like a champion every day.",
    "Be the hardest worker in the room.",
    "Small steps lead to big results.",
    "You don’t find willpower; you create it.",
    "Rise above the noise.",
    "Turn your ‘I can’t’ into ‘I can.’",
    "Play with heart; win with pride.",
    "Your hard work will pay off.",
    "Let your results speak for themselves.",
    "Success is a journey, not a destination.",
    "Believe. Achieve. Succeed!",
    "Every champion was once a beginner.",
    "Fall seven times, stand up eight.",
    "If you don’t sacrifice for what you want, what you want becomes the sacrifice.",
    "Dream it, wish it, do it.",
    "True champions aren’t born; they’re made.",
    "You miss 100% of the shots you don’t take.",
    "Success isn’t given; it’s earned.",
    "Keep your eyes on the prize.",
    "Pain is temporary; pride is forever.",
    "Never stop hustling.",
    "Doubt kills more dreams than failure ever will.",
    "Champions keep playing until they get it right.",
    "It’s not whether you get knocked down; it’s whether you get up.",
    "Your body can stand almost anything. It’s your mind that you have to convince.",
    "Greatness is not in where we stand, but in what direction we are moving.",
    "You don’t have to be great to start, but you have to start to be great.",
    "Turn your scars into stars.",
    "The only bad workout is the one you didn’t do.",
    "Life is like sports; it requires hard work and practice.",
    "Fall in love with the process, and the results will come.",
    "Mindset is everything.",
    "Shut up and train.",
    "Be stronger than your excuses.",
    "Winning means you’re willing to go longer, work harder, and give more than anyone else.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Pain is your friend; it’s the way you grow.",
    "When you feel like quitting, think about why you started.",
    "Work hard in silence; let success make the noise.",
    "You are what you repeatedly do.",
    "The way to get started is to quit talking and begin doing.",
    "Success isn’t just about what you accomplish in your life; it’s about what you inspire others to do.",
    "Successful people are not gifted; they just work hard.",
    "If you want something you’ve never had, you must be willing to do something you’ve never done.",
    "Persistence can change failure into extraordinary achievement.",
    "You can’t put a limit on anything. The more you dream, the farther you get.",
    "Champions adapt; they never lose their heart.",
    "You are your only competition.",
    "Every workout is progress.",
    "Your pace doesn’t matter; forward is forward.",
    "The road to success is dotted with many tempting parking spaces.",
    "Stay focused. Stay humble. Stay driven.",
    "You have to expect things of yourself before you can do them.",
    "You must expect great things of yourself before you can do them.",
    "Prove them wrong.",
    "Work hard. Be kind.",
    "Dream big, work hard, and stay humble.",
    "Never back down from a challenge.",
    "You are what you believe yourself to be.",
    "It’s not about the destination; it’s about the journey.",
    "Your limitations are only in your mind.",
    "The struggle you’re in today is developing the strength you need for tomorrow.",
    "Consistency is the mother of mastery.",
    "Life begins at the end of your comfort zone.",
    "Set goals, crush them, and repeat.",
    "If it doesn’t challenge you, it won’t change you.",
    "Don’t watch the clock; do what it does. Keep going.",
    "It always seems impossible until it’s done.",
    "Believe you can, and you’re halfway there.",
    "Dream it. Do it.",
    "You have the power to change your story.",
    "Winners are not afraid of losing but losers are.",
    "Chase your passion, not your paycheck.",
    "Good things come to those who hustle.",
    "Life is a sport; make it count.",
    "Keep pushing yourself; that’s where the magic happens.",
    "Don't stop until you're proud.",
    "Every accomplishment starts with the decision to try.",
    "Your future self will thank you.",
    "Success is not owned; it’s leased, and rent is due every day.",
    "A little progress each day adds up to big results.",
    "Dedicate yourself to constant and never-ending self-improvement.",
    "You can’t swim for new horizons until you have courage to lose sight of the shore.",
    "Dream big, work hard, and stay humble.",
    "Every champion was once a contender who refused to give up.",
    "You have to see failure as the beginning and the middle, but never entertain it as the end.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "Your vibe attracts your tribe.",
    "Success requires no explanations; failure permits no alibis.",
    "You can’t rely on luck; you have to put in the work.",
    "Don’t limit your challenges; challenge your limits.",
    "Greatness is a choice.",
    "Success is not for the lazy.",
    "It’s not about how bad you want it; it’s about how hard you’re willing to work for it.",
    "Start where you are. Use what you have. Do what you can.",
    "Champions are made from failures.",
    "A champion is defined not by their wins but by how they can recover when they fall.",
    "Keep pushing. Every step counts.",
    "Have the courage to follow your dreams.",
    "Get comfortable being uncomfortable.",
    "Limit your excuses and maximize your efforts.",
    "What defines us is how well we rise after falling.",
    "You can’t spell hustle without us.",
    "Stay strong; make them wonder how you’re still smiling.",
    "Turn setbacks into comebacks.",
    "If you can conceive it, you can achieve it.",
    "Pain is weakness leaving the body.",
    "Every obstacle is an opportunity to improve.",
    "Success is not in what you have, but who you are.",
    "You have what it takes to be successful.",
    "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.",
    "Advertisements may say ‘no pain, no gain’ but it’s really no effort, no results.",
    "No dream is too big if you are committed.",
    "Your dreams are a roadmap to your destiny.",
    "Commitment is the foundation of great accomplishments.",
    "Let your actions speak for you.",
    "Success requires patience and persistence.",
    "Don’t wait for opportunity; create it.",
    "Your future is created by what you do today.",
    "Be the hardest worker in the room.",
    "Keep your dreams alive.",
    "Life is too short to wait.",
    "Every effort you make today will pay off tomorrow.",
    "Success doesn’t come to you; you go to it.",
    "Visualize your success and don’t settle for less.",
    "You’ve got to get up every morning with determination if you’re going to go to bed with satisfaction.",
    "Dream it. Live it.",
    "If you want it, you will find a way.",
    "Don’t be pushed around by the fears in your mind.",
    "Go the extra mile; it’s never crowded.",
    "Your potential is limitless.",
    "Act like you own the place.",
    "Be the person you are meant to be.",
    "Nothing is impossible; the word itself says 'I’m possible!'",
    "Continuous improvement is better than delayed perfection.",
    "Concentrate all your thoughts upon the work at hand.",
    "Success isn’t just about what you accomplish in your life; it’s about what you inspire others to do.",
    "The hardest step is the first step.",
    "Let your heart be your guide.",
    "Keep the fire of motivation alive.",
    "If you want something you’ve never had, you must be willing to do something you’ve never done.",
    "Strength doesn’t come from what you do. It comes from overcoming the things you once thought you couldn’t.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Difficult roads often lead to beautiful destinations.",
    "Perseverance is not a long race; it is many short races one after the other.",
    "Your only limit is your mind.",
    "Keep going; you can do it!",
    "Fortitude is the unruly minor of endurance.",
    "Small daily improvements are key to staggering long-term results.",
    "When it’s tough, remember why you started.",
    "Trust the process.",
    "Success is built on a solid foundation of determination.",
    "Life rewards those who hustle.",
    "Prepare to win or lose by failing to prepare.",
]


async def get_random_motivation():
    return random.choice(motivational_phrases)
